### ISSUE TITLE
Specifying Python version in the Ansible playbooks

### ISSUE THREAD

**Issue by pjakovits** [radon-h2020/demo-ctt-sockshop#2]
I ran into some issues with Ansible using the wrong Python version when xOpera is deploying the test infrastructure using create_ti.yml playbook. The issue seems to be related to how xOpera uses Ansible, but adding:

```
  vars:
    ansible_python_interpreter: /usr/bin/python3
```

inside the create_ti.yml Ansible playbook fixed these issues for me. I also added:
` become: yes ` 
line to elevate Ansible commands to have permissions to install linux packages. 
The start of the reate_ti.yml file after the change:

```
- name: Run SockShop
  hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
```
