### ISSUE TITLE
Indentation issue in create_ti.yml

### ISSUE THREAD

**Issue by pjakovits** [radon-h2020/demo-ctt-sockshop#3]
I got Ansible errors when trying to deploy the sockshop example Testing Infrastructure. 

It seems the issue is related to the indentation of Ansible parameters inside the create_ti.yml file. The 
`when: ansible_distribution == "Ubuntu"`
and
`when: ansible_distribution == "Arch Linux"`
statements should be aligned to the same level as `package:` like this:

```
    - name: install pip module prerequisites
      package:
        name: 
          - python3-pip
          - python3-virtualenv
          - python3-setuptools
        state: present
      when: ansible_distribution == "Ubuntu"
```

Otherwise it results in an error that **package** module has not-allowed parameters. This behaviour may be different based on the used Ansible version.
